### ISSUE TITLE
How to install this qcmaquis with OpenMolcas?

### ISSUE THREAD

**Issue by 1234zou** [qcscine/qcmaquis#1]
Dear QCMaquis developers,

How to install this qcmaquis with OpenMolcas? I've read the installation guide in QCMaquis-3.0 and OpenMolcas-20.10 manuals and found that still old installation (i.e. online downloaded from GITLAB) instructions are written therein.

Following the instructions in README.md, I've successfully compiled this qcmaquis (with bin, lib, include directories generated), but I don't know what to do next.

Any suggestion or help would be appreciated. Thanks.

**Comment by kommerck** [comment]
Currently support for the new QCMaquis release in OpenMolcas has not yet been merged into the OpenMolcas master branch. You may try out the new interface by cloning the `qcmaquis-release` branch of OpenMolcas, from its gitlab repository, and then following the installation guide. If you try to install QCMaquis from the OpenMolcas-20.10 master branch, the old QCMaquis version will be downloaded and installed (which still should work, too)

**Comment by 1234zou** [comment]
Thank you very much.

I've successfully compiled the qcmaquis-release branch of OpenMolcas. The DMRG and NEVPT2 modules work well (I've tried a N2 molecule with CAS(6,6) and energies can be compared with other programs). However, some strange errors take place in my &RASSCF output, like

HDF5-DIAG: Error detected in HDF5 (1.12.0) thread 0:
  #000: H5D.c line 435 in H5Dget_type(): invalid dataset identifier
    major: Invalid arguments to routine
    minor: Inappropriate type

But the CASSCF(6,6) energy is correct. I think this is not related to QCMaquis but to OpenMolcas, so I'll close this issue.
