### ISSUE TITLE
Failed compilation on G++ 11.3

### ISSUE THREAD

**Issue by adam-grofe** [qcscine/qcmaquis#15]
When I attempt to compile version 3.1.2 using g++ 11.3, I receive the following error:

>    /path/to/dmrg/framework/dmrg/utils/results_collector.h:79:10: error: 'map' in namespace 'std' does not name a template type
>       79 |     std::map<std::string, std::shared_ptr<collector_impl_base> > collection;
>            |          ^~~
>    /path/to/dmrg/framework/dmrg/utils
>             /results_collector.h:31:1: note: 'std::map' is defined in header '<map>'; did you forget to '#include <map>'?
>         30 | #include <boost/any.hpp>
>      +++ |+#include \<map\>
>         31 | #include \<vector\>

It appears that `dmrg/framework/dmrg/utils/results_collector.h` is missing `#include <map>`, where std::map is the type used by `collection`. It is odd that this hasn't been a problem in prior versions, but this should be simple fix.

**Comment by AlbertoBaiardi** [comment]
@adam-grofe Thanks for spotting this bug! I'll try to reproduce it and fix it right away.

**Comment by azaichen** [comment]
The problem arises with gcc/10.2.0, but it is simple to fix the bug, just add line 

```#include <map>```

in file qcmaquis/dmrg/framework/dmrg/utils/results_collector.h 

Best,
Aleksandr

**Comment by adam-grofe** [comment]
> Yes. The problem arises also with gcc/10.2.0, but it is simple to fix the bug, just add line
> 
> `#include <map>`
> 
> in file qcmaquis/dmrg/framework/dmrg/utils/results_collector.h
> 
> Best, Aleksandr

Yes, I came to the same conclusion as well. This would be nice to have in the main branch though.

**Comment by kszenes** [comment]
Fixed in release-3.1.4
