### ISSUE TITLE
Energy does not depend on max_bond_dimension in 011.input?

### ISSUE THREAD

**Issue by dmrg-learner** [qcscine/qcmaquis#19]
Hi,

  I tried to run https://raw.githubusercontent.com/Molcas/OpenMolcas/dbb6ed0fcd4552d29700dd95d6896ed20c9e5857/test/qcmaquis/011.input
  from `openmolcas  v22.10 `

  I got 
      `Total MC-PDFT energy for state     1                               -150.37153838`
  
when I changed the input as 
    `max_bond_dimension = 10`
I got 
  `      Total MC-PDFT energy for state     1                               -150.37153838`

Namely, the energy does not depends on `max_bond_dimension`.
Anything wrong in modifying the input? Thank you very much

**Comment by weymutht** [comment]
Hi :smiley: I think that you don't see a change in the energy because the problem is very small (a small active space and a highly symmetric system). You should see an impact of the bond dimension when going to larger systems.

**Comment by dmrg-learner** [comment]
Thanks! I modified `nactel = 6` and `ras2   = 6` (is that (6,6) active space?), the energy becomes different.

```
      Total MC-PDFT energy for state     1                               -150.35137034
```
and
```
      Total MC-PDFT energy for state     1                               -150.35085025
```

for 10 and 100 `max_bond_dimension`, respectively.
