### ISSUE TITLE
Update shebang line in python script(s)

### ISSUE THREAD

**Issue by Jellby** [qcscine/qcmaquis#26]
At least this one fails on me because I don't have `python` in my system, but `python3`.

https://github.com/qcscine/qcmaquis/blob/2c1347d2ff3c780372a435051925912af1b92b9c/dmrg/lib/interfaces/openmolcas/tools/qcm_checkpoint_rename.py#L1

Perhaps the shebang line could be updated to use `Python_EXECUTABLE` when building/installing? (See e.g. https://gitlab.com/Molcas/OpenMolcas/-/blob/master/Tools/mort/CMakeLists.txt)

**Comment by weymutht** [comment]
I just merged it into the main branch, so I take the liberty of closing this issue.
